version: '3.1'
services:
 
  app:
    container_name: app-springboot-postgresql
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/myshopdb
    depends_on:
      - dbpostgresql   
  dbpostgresql:
    image: postgres
    volumes:
      - ./initial_sql_script.sql:/docker-entrypoint-initdb.d/initial_sql_script.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
